//
// Created by Adam Saher on 2022-12-29.
//

#ifndef C_Q1_H
#define C_Q1_H

/*
A coloured triangle is created from a row of squares, each of which is red, green or blue. Successive rows, each
containing one fewer square than the last, are generated by considering the two touching squares in the previous row. If
these squares are identical, the same colour is used in the new row. If they are different, the missing colour is used
in the new row. This is continued until the final row, with only a single square, is generated.
In the following three example triangles R, G and B have been used to represent the colours. Note that each row is
generated from the row above.

G G                                      R B                          R R G B R G B B
 G                                        G                            R B R G B R B
                                                                        G G B R G G
                                                                         G R G B G
                                                                          B B R R
                                                                           B G R
                                                                            R B
                                                                             G

Sample Input 1:
RRGBRGBB
Output for Sample Input 1:
G

Sample Input 2:
RBRGBRB
Output for Sample Input 2:
G

Sample Input 3:
GRBRBRBRBR
Output for Sample Input 3:
B

Sample Input 4:
RBGBGBGBGR
Output for Sample Input 4:
R
 */
#include <string>
char triangle(const std::string&);


#endif //C_Q1_H
